name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # https://github.com/actions/setup-java/blob/main/README.md#Supported-distributions
        java-version: '14'
        java-package: jdk # optional (jdk or jre) - defaults to jdk
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: 1.11.1.1165             # Clojure CLI based on tools.deps
        bb: 0.7.8                    # Babashka
        clj-kondo: 2022.05.31        # Clj-kondo
        cljfmt: 0.10.2               # cljfmt
        cljstyle: 0.15.0             # cljstyle
    - name: bb ci-check
      run: bb ci-check
    - name: bb ci-goldly-deploy
      env:
        CLOJARS_USERNAME: ${{ secrets.ReleaseUsername }}
        CLOJARS_PASSWORD: ${{ secrets.ReleasePassword }}
        CODECOV_TOKEN: ${{ secrets.CodecovToken }}
      run: |
        git config --global user.email "ci@pinkgorilla.org"
        git config --global user.name "CI/CD"
        bb ci-goldly-deploy
    - name: bb ci-goldly-docs-deploy
      if: success()
      # if: github.event_name == 'push'
      env:
        CLOJARS_USERNAME: ${{ secrets.ReleaseUsername }}
        CLOJARS_PASSWORD: ${{ secrets.ReleasePassword }}
        CODECOV_TOKEN: ${{ secrets.CodecovToken }}
      run: |
        git config --global user.email "ci@pinkgorilla.org"
        git config --global user.name "CI/CD"
        bb ci-goldly-docs-deploy
      # bash <(curl -s https://codecov.io/bash)
      # lein with-profile +relay-jetty cloverage
      #  bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
      #
      # Could not transfer metadata foo:bar/maven-metadata.xml from/to releases (https://clojars.org/repo): Read timed out
      # Default 10000 not enough for us
      # export LEIN_JVM_OPTS="-Dmaven.wagon.rto=90000"     
